# bundle exec jekyll serve --host=0.0.0.0

title: MycilaSafeBoot
description: MycilaSafeBoot is a Web OTA recovery partition for ESP32 / Arduino
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
